services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: image-rag-backend

    env_file:
      - .env

    expose:
      - "8000"

    volumes:
      - huggingface-cache:/root/.cache/huggingface

    networks:
      - image-rag-network

    healthcheck:
      test:
        [
          "CMD",
          "uv",
          "run",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/docs')"
        ]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 10s

    restart: unless-stopped


  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile

    container_name: image-rag-nginx

    ports:
      - "80:80"

    depends_on:
      backend:
        condition: service_healthy

    networks:
      - image-rag-network

    restart: unless-stopped


networks:
  image-rag-network:
    driver: bridge


volumes:
  huggingface-cache: